### ISSUE TITLE
newer driver versions don't have the correct files

### ISSUE THREAD

**Issue by rayvearn** [Loliconera/Unlocked-Dolby-Digital-Live-DTS-Interactive-for-Realtek-HD-Audio-Drivers-for-Windows-10-and-11#1]
newer driver versions have differently named dll files, i'm not sure if they changed the name to deter patcher use or if it's actually different, but it breaks the patcher nonetheless.

(instead of ,"rltkAPO64.dll" it has "RltkAPOU64.dll").

**Comment by Loliconera** [comment]
this patch is only compatible with old drivers 2.80 and earlier

**Comment by Iruberiam** [comment]
You can patch the official v2.80 files, rename to the new format and copy to the driver install folder.

**Comment by Loliconera** [comment]
> You can patch the official v2.80 files, rename to the new format and copy to the driver install folder.

The problem is that if you patch the file and rename it and add it to the new drivers, you may get the message that the audio format is not compatible with the device.

**Comment by Iruberiam** [comment]
Perhaps it's system specific but this is what works on my ALC887 and gives me "Dolby Digital Live" and "DTS Interactive", I only use DDL though as my Astro headset doesn't support DTS.

**Comment by Loliconera** [comment]
> Perhaps it's system specific but this is what works on my ALC887 and gives me "Dolby Digital Live" and "DTS Interactive", I only use DDL though as my Astro headset doesn't support DTS.

does not work on my **Realtek® ALC1220** I get the following message when I try to select DTS interactive or dolby digital live:


![Screenshot_1](https://user-images.githubusercontent.com/69399372/230740524-4eb38883-4aa3-40c9-8032-66218541831b.jpg)


![image](https://user-images.githubusercontent.com/69399372/230740599-e149a5bd-631b-491a-9825-61f7f299a931.png)

**Comment by Iruberiam** [comment]
Oh that's unfortunate.

**Comment by Loliconera** [comment]
this **patch only works** with the official version **v2.80** files
