### ISSUE TITLE
Hdmi support or SPDIF unlock.

### ISSUE THREAD

**Issue by mycop5** [Loliconera/Unlocked-Dolby-Digital-Live-DTS-Interactive-for-Realtek-HD-Audio-Drivers-for-Windows-10-and-11#2]
Hi!
My M.b surprisely have no SPDIF
so...
1. Can this app(or another ) make DDL\DTS (Dts most prefer) work to HDMI output?
2.  It is have patch\drivermod\bios mod to enable  SPDIF physicaly? Coz all chip have SPDIF pin its just diabled. Some os like linux can solve it. but need "windows".

**Comment by Loliconera** [comment]
This guide **only works for the S/PDIF interface** and will unlock Dolby Digital Live and DTS Connect

**Comment by Loliconera** [comment]
you can try this guide as it has HDMI AUDIO support

https://www.techpowerup.com/forums/threads/aaf-optimus-dch-audio-modded-driver-for-windows-10-11-for-all-hdaudio-enumerator-chips.292621/
