### ISSUE TITLE
All image is die

### ISSUE THREAD

**Issue by tkp206093** [Loliconera/Unlocked-Dolby-Digital-Live-DTS-Interactive-for-Realtek-HD-Audio-Drivers-for-Windows-10-and-11#6]
RT
![image](https://github.com/Loliconera/Unlocked-Dolby-Digital-Live-DTS-Interactive-for-Realtek-HD-Audio-Drivers-for-Windows-10-and-11/assets/29872453/5cc4f29f-eca8-4740-a58d-1c0440e41525)

**Comment by Loliconera** [comment]
> RT ![image](https://private-user-images.githubusercontent.com/29872453/290930122-5cc4f29f-eca8-4740-a58d-1c0440e41525.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MzMxODMsIm5iZiI6MTcwMzUzMjg4MywicGF0aCI6Ii8yOTg3MjQ1My8yOTA5MzAxMjItNWNjNGYyOWYtZWNhOC00NzQwLWE1OGQtMWMwNDQwZTQxNTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDE5MzQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5M2IxOWZjZmJlODM0YjAzYmU0MzlhOGJmYTViNGE0M2JhZDQxYjVjMDRiMmVlNDEzMWYxN2EyOTkyZjAzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8Xgcp_9eTiZouKjzQw0vcmqgvF5EkviEGq-GBYoqR0)

I will update the images
